server:
  #服务器端口
  port: 26666
system:
  #数据库连接配置
  datasource:
    type: mysql
    url: jdbc:mysql://数据库地址:3306/数据库名称?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: 数据库用户名
    password: 数据库密码
mybatis-plus:
  configuration:
    #输出mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#推送代理
proxy:
  push:
    enable: false
    port: 7890
    ip: 127.0.0.1
    type: http/socket
    #指定那种推送方式需要使用代理
    use:
      - TelegramPush
      - DiscordPush
