server:
  # 开启静态资源压缩
  compression:
    enabled: true
    mime-types: application/javascript,text/css,text/html
    min-response-size: 2KB
  servlet:
    context-path: /api
system:
  auth:
    exclude-url:
      - /test/**
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc: #静态资源
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1800
          cache-public: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: auto_plan
  # token 有效期（单位：秒） 1天
  timeout: 86400
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 3600
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-64
  # 是否输出操作日志
  is-log: false
