# ===================================================================
# FINAL - LOCAL DATABASE CONFIGURATION
# This file is configured to use a self-contained SQLite database.
# ===================================================================
server:
  port: 26666

spring:
  datasource:
    # Use the SQLite database driver
    driver-class-name: org.sqlite.JDBC
    # Create a database file named 'autoplan.db' inside the container
    url: jdbc:sqlite:autoplan.db
    username: 
    password: 

  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

actable:
  table:
    # 'create' mode will build the database structure on the first run
    auto: create
  model:
    pack: com.oldwu.entity;com.oldwu.domain;com.netmusic.model;com.miyoushe.model;com.bili.model
  database:
    # Critical: Set database type to sqlite
    type: sqlite
  index:
    prefix: INDEX_
  unique:
    prefix: INDEX_UNIQUE_

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  type-aliases-package: com.oldwu.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl