# ===================================================================
# application.yml (Optimized for Environment Variables)
# Default Configuration: Runs with a minimal, file-based SQLite database.
# All critical settings can be overridden by environment variables.
# ===================================================================

server:
  # The server port. Can be overridden by the PORT or SERVER_PORT environment variable.
  port: ${SERVER_PORT:26666}

spring:
  # Default datasource configuration (SQLite).
  # These can all be overridden for MySQL, PostgreSQL, etc.
  datasource:
    # Driver for the database.
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.sqlite.JDBC}
    # Connection URL. For SQLite, this is the path to the database file.
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:autoplan.db}
    # Username for the database (SQLite doesn't need one).
    username: ${SPRING_DATASOURCE_USERNAME:}
    # Password for the database (SQLite doesn't need one).
    password: ${SPRING_DATASOURCE_PASSWORD:}

  # These settings are generally static and tied to the application's code.
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

actable:
  table:
    auto: update
  model:
    pack: com.oldwu.entity;com.oldwu.domain;com.netmusic.model;com.miyoushe.model;com.bili.model
  # The database type. It's critical this matches the datasource driver.
  # Options can be 'sqlite', 'mysql', etc.
  database:
    type: ${ACTABLE_DATABASE_TYPE:sqlite}
  index:
    prefix: INDEX_
  unique:
    prefix: INDEX_UNIQUE_

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  type-aliases-package: com.oldwu.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Push proxy settings. All can be configured via environment variables.
proxy:
  push:
    enable: ${PROXY_PUSH_ENABLE:false} # Default: disabled
    port: ${PROXY_PUSH_PORT:7890}
    ip: ${PROXY_PUSH_IP:127.0.0.1}
    type: ${PROXY_PUSH_TYPE:http/socket}
    use: ${PROXY_PUSH_USE:} # Default: empty, meaning no services use it